version: "3"
services:
  mci:
    image: brighthive/master-client-index:1.0.0
    ports: 
    - 8000:8000
    depends_on: 
    - postgres
    environment:
      - APP_ENV=SANDBOX
      - POSTGRES_USER=brighthive
      - POSTGRES_PASSWORD=test_password
      - POSTGRES_DATABASE=mci_dev
      - POSTGRES_PORT=5432
      - WORKERS=4
      - POSTGRES_HOSTNAME=postgres
      - MATCHING_SERVICE_URI=http://mci-matching-service:8000/compute-match
    stdin_open: true 
    tty: true
  mci-matching-service:
    image: brighthive/mci-matching-service:1.0.0 
    environment:
      - APP_ENV=SANDBOX
      - POSTGRES_USER=brighthive
      - POSTGRES_PASSWORD=test_password
      - POSTGRES_DATABASE=mci_dev
      - POSTGRES_PORT=5432
      - POSTGRES_HOSTNAME=postgres
    stdin_open: true 
    tty: true
  postgres:
    image: postgres:11.1
    environment: 
      - POSTGRES_USER=brighthive
      - POSTGRES_PASSWORD=test_password
      - POSTGRES_DB=mci_dev