version: "3.5"
services:
    mci:
        image: brighthive/master-client-index:1.0.0
        ports:
            - "8000:8000"
        environment:
            - APP_ENV=DEVELOPMENT
            - POSTGRES_USER=brighthive
            - POSTGRES_PASSWORD=test_password
            - POSTGRES_DATABASE=mci_dev
            - POSTGRES_HOSTNAME=postgres_mci
            - POSTGRES_PORT=5432
            - MATCHING_SERVICE_URI=http://mci-matching-service:8000/compute-match
        depends_on:
            - postgres_mci
            - mci-matching-service
    mci-matching-service:
        image: brighthive/mci-matching-service:1.0.0
        environment:
            - APP_ENV=DEVELOPMENT
            - POSTGRES_USER=brighthive
            - POSTGRES_PASSWORD=test_password
            - POSTGRES_DATABASE=mci_dev
            - POSTGRES_PORT=5432
            - POSTGRES_HOSTNAME=postgres_mci
    redis:
        image: redis:latest
        ports:
            - "6379:6379"
    postgres_mci:
        image: postgres:latest
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=brighthive
            - POSTGRES_PASSWORD=test_password
            - POSTGRES_DB=mci_dev
        user: postgres
